
import java.awt.Dimension;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samir
 */
public class FinalReport extends javax.swing.JInternalFrame {

    // Main class
    Main main;

    // Results
    private int[] results;
    
    // Standards
    private String[] standards;
    
    // Stores the grade
    private int grade;
    
    // Stores the difficulty (3 is hard for final)
    private int difficulty = 3;
    
    // ImageIcons for the checkmark and red x
    private ImageIcon incorrectImageIcon;
    private ImageIcon correctImageIcon;
    
    // Default table model
    DefaultTableModel tableModel;
    
    /**
     * Creates new form FinalReport
     */
    public FinalReport(Main m, int[] results, String[] standards, int grade) {
        
        // Initializes the components
        initComponents();
        
        // Stores a reference to the main
        main = m;
        
        // Centers the JInternalFrame
        center();
        
        // Stores the results from the previous assessment
        this.results = results;
        
        // Stores the standards asked from the previous assessment
        this.standards = standards;
        
        // Stores the grade
        this.grade = grade;
        
        for (int i = 0; i < standards.length; i++) {
            switch (standards[i]) {
                case "KN1":
                    this.standards[i] = "Counting";
                break;
                case "KN2":
                    this.standards[i] = "Matching";
                break;
                case "KN3":
                    this.standards[i] = "Position";
                break;
                case "KN4":
                    this.standards[i] = "Comparing";
                break;
                case "KN5":
                    this.standards[i] = "Half & Whole";
                break;
                case "KN6":
                    this.standards[i] = "Coins";
                break;
                case "KN7":
                    this.standards[i] = "Math with Drawings";
                break;
                case "KN8":
                    this.standards[i] = "Estimate";
                break;
                case "2N4":
                    this.standards[i] = "Comparing";
                break;
                case "4N12":
                    this.standards[i] = "Math with Large Numbers";
                break;
                default:
                    this.standards[i] = "";    
                break;
            }            
        }

        
        // ImageIcons for the correct, and incorrect buttons
        incorrectImageIcon = new ImageIcon(getClass().getResource("Images/QuizReport/X.png"));
        correctImageIcon = new ImageIcon(getClass().getResource("Images/QuizReport/Checkmark.png"));
       
        // Gets the model from the JTable on the screen
        tableModel = (DefaultTableModel) jTable1.getModel();
        
        displayReport();
        
    }

    // This method centers the JInternalFrame on the screen
    public void center() {
        
        // Gets the dimension of the main desktop pane
        Dimension desktopSize = main.getDesktopPaneDimension();
                
        // Gets the size of this JInternalFrame
        Dimension jInternalFrameSize = this.getSize();
        
        // Centers this JInternalFrame in the DesktopPane
        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);
        
    }
    
    // This method displays the users report on the final assessment
    public void displayReport() {
        
        tableModel.setRowCount(results.length);
        
        for (int i = 0; i < results.length; i++) {
            
            jTable1.setValueAt(i+1, i, 0);
            jTable1.setValueAt(standards[i], i, 1);
            
            if (results[i] == 0) {
                jTable1.setValueAt(incorrectImageIcon, i, 2);
            } else {
                jTable1.setValueAt(correctImageIcon, i, 2);
            }
            
            jTable1.setRowHeight(42);
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Final Report");
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Question Number", "Type", "Right/Wrong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 2: return ImageIcon.class;
                    default: return types[columnIndex];
                }
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Final Report");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisterScreen/goButton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainScreen/printer.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // When the GO button is clicked
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Opens the grade select screen
        main.openGradeSelectScreen();  

        // Disposes this screen
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    // Called when the printer button is pressed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
    }//GEN-LAST:event_jButton2ActionPerformed

    // Method that is called when the form is closed
    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        // Sets the variable to false
        main.setIsFinalReportScreenOpen(false);

    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
