/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

import java.sql.*;
import java.util.Properties;
import javax.swing.*;

/**
 *
 * @author Samir
 */
public class ForgotPassword extends javax.swing.JInternalFrame {
    
    // variables needed to make connection with DB
   private static final String dbClassName = "com.mysql.jdbc.Driver";
   private static final String CONNECTION = "jdbc:mysql://localhost/germs"; 
   String securityanswer;
   String id;
   String securityquestion;
   String password;

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        getquestionButton = new javax.swing.JButton();
        usernameTextField = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        securityquestionTextField = new javax.swing.JTextField();
        usernameLabel2 = new javax.swing.JLabel();
        securityanswerTextField = new javax.swing.JTextField();
        getpasswordButton = new javax.swing.JButton();
        helpAudioButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Forgot Password");
        setToolTipText("Forgot Password");
        setAlignmentX(250.0F);
        setVisible(true);

        usernameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        usernameLabel.setText("Security Question:");

        getquestionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getquestionButton.setText("Get Security Question");
        getquestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getquestionButtonActionPerformed(evt);
            }
        });

        usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        usernameLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        usernameLabel1.setText("Username:");

        securityquestionTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        securityquestionTextField.setEnabled(false);

        usernameLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        usernameLabel2.setText("Security Answer:");

        securityanswerTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        getpasswordButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getpasswordButton.setText("Get Password");
        getpasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getpasswordButtonActionPerformed(evt);
            }
        });

        helpAudioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phase3/Image/GradeSelect/AudioButton.png"))); // NOI18N
        helpAudioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpAudioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getpasswordButton)
                    .addComponent(getquestionButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(usernameLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(helpAudioButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameLabel)
                                .addComponent(usernameLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(securityanswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(securityquestionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameLabel1)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(helpAudioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getquestionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(securityquestionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel2)
                    .addComponent(securityanswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getpasswordButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setBounds(170, 15, 610, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void helpAudioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpAudioButtonActionPerformed
        // TODO add your handling code here:
        File yourFile = new File("src/sounds/GeRMSForgotPassword.wav");
            AudioInputStream stream;
            AudioFormat format;
            DataLine.Info info;
            Clip clip;

            try {
                stream = AudioSystem.getAudioInputStream(yourFile);
                format = stream.getFormat();
                info = new DataLine.Info(Clip.class, format);
                clip = (Clip) AudioSystem.getLine(info);
                clip.open(stream);
                clip.start();
            } catch (UnsupportedAudioFileException | IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_helpAudioButtonActionPerformed

    private void getquestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getquestionButtonActionPerformed
        try {
        Class.forName(dbClassName);
        
        // user/pwd to connect to DB
        Properties p = new Properties();
        p.put("user","GermsAdmin");
        p.put("password","g3rm5p0w3ru53r");
        
        // DB connection
        Connection conn = DriverManager.getConnection(CONNECTION,p);  
        
        // Get username and password
        String user = usernameTextField.getText();  
        // Get username and password
        Statement stmt = conn.createStatement();
        String sql = "SELECT * FROM accounts a JOIN securityquestion s"
                + " ON a.secID = s.secID WHERE a.accUser = '" + user + "'";
        ResultSet rs = stmt.executeQuery(sql);
        
        //if user exists, all fields associate to that user from table
        if (rs.next() == true){
            id = rs.getString("accUser");
            securityquestion = rs.getString("s.secQuestion");
            securityanswer = rs.getString("a.secAnswer");
            password = rs.getString("a.accpassword");
            
            securityquestionTextField.setText(securityquestion);
        }else{
            JOptionPane.showMessageDialog(null, "No user found", "User", JOptionPane.INFORMATION_MESSAGE);
        }
        
        } catch (ClassNotFoundException e) {
            
        } catch (SQLException e) {
            
        }
    }//GEN-LAST:event_getquestionButtonActionPerformed

    private void getpasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getpasswordButtonActionPerformed

        if(securityanswer.equals(securityanswerTextField.getText())){
            JOptionPane.showMessageDialog(null, "Your password is: " + password, "Password", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Wrong Answer", "Answer", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_getpasswordButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getpasswordButton;
    private javax.swing.JButton getquestionButton;
    private javax.swing.JButton helpAudioButton;
    private javax.swing.JTextField securityanswerTextField;
    private javax.swing.JTextField securityquestionTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JLabel usernameLabel2;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
