/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Main extends javax.swing.JFrame {

    private boolean isHelpScreenOpen = false;
    
    // Login class
    public Login login;
    
    // Determines if the Login Screen is open
    private boolean isLoginScreenOpen;
    
    // Determines if the user is logged in
    public boolean isLoggedIn = false;
    
    // Determines if the user is logged in as an adminsitrator
    public boolean isLoggedInAsAdmin = false;
    
    // GradeSelect class
    public GradeSelect gradeSelect;
    
    // Determines if the Grade Select screen is open
    public boolean isGradeSelectScreenOpen = false;
    
    // ManageAccounts class
    public ManageAccounts manageAccounts;
    
    // Determines if the Manage Screen is open
    public boolean isManageScreenOpen = false;
            
    /*
    * Creates a new instance of the Main class
    */
    public Main() {
        
        // Initialize the components on the main screen
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        // Creates a new instance of the login screen
        login = new Login(desktopPane, this, gradeSelect);
        
        // Adds the login screen to the desktop pane
        desktopPane.add(login);
        
        // Sets isLoginScreenOpen variable to true
        isLoginScreenOpen = true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        starsLabel = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane() {
            private java.awt.Image image;
            {
                try {
                    java.net.URL url = this.getClass().getClassLoader().getResource("Images/MainScreen/background.jpg");
                    image = javax.imageio.ImageIO.read(url);
                } catch (java.io.IOException e) {
                    e.printStackTrace();
                }
            }
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, null);           
            }
        };
        jLabel1 = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        printerButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        manageAccountsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GeRMS Math Tutor");
        setExtendedState(4);
        setFocusCycleRoot(false);

        usernameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        usernameLabel.setText("Username:");

        starsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        starsLabel.setText("Stars:");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainScreen/helpButton.png"))); // NOI18N
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        printerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainScreen/printer.png"))); // NOI18N
        printerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printerButtonActionPerformed(evt);
            }
        });

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainScreen/homeButton.png"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainScreen/logoutButton.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MainScreen/loginButton.png"))); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        manageAccountsMenuItem.setText("Manage Accounts");
        manageAccountsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(manageAccountsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(starsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                        .addComponent(loginButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(helpButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(starsLabel))
                    .addComponent(helpButton)
                    .addComponent(printerButton)
                    .addComponent(homeButton)
                    .addComponent(logoutButton)
                    .addComponent(loginButton))
                .addGap(11, 11, 11)
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setIsLoginScreenOpen(boolean isOpen) {
        isLoginScreenOpen = isOpen;
    }
    
    public void setIsRegisterScreenOpen(boolean isOpen) {
        
    }
    
    public void setIsForgotPasswordScreenOpen(boolean isOpen) {
        
    }
    
    public void setIsManageAccountsScreenOpen(boolean isOpen) {
        
    }
    
    public void setIsGradeSelectScreenOpen(boolean isOpen) {
        
    }
    
    public void setIsHelpScreenOpen(boolean isOpen) {
        
    }
    
    public void closeAllScreens() {
        
        
    }    
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
    
        // The action listener for the exit menu item
        
        // Exits the program
        System.exit(0);
        
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
       
        // If the login screen is not open
        if (!isLoginScreenOpen) {
            
            // Creates a new instance of the login screen
            login = new Login(desktopPane, this, gradeSelect);
            
            // Adds the login screen to the desktop pane
            desktopPane.add(login);
            
            // Brings the login screen to the front
            login.toFront();
            
            // Sets the is login screen open variable to true
            isLoginScreenOpen = true;
            
        // If the login screen is already open
        } else {
            
            // Display a message
            javax.swing.JOptionPane.showMessageDialog(null, "Login is already open", "Login", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        
        // The logout button action listener (the button is located on the top banner next to the login button) 
        
        // If the person is logged in
        if (isLoggedIn) {
            
            // Sets the isLoggedIn variable to false
            isLoggedIn = false;
            
            // If they were logged in as an admin, they they set it to false now
            if (isLoggedInAsAdmin) {
                isLoggedInAsAdmin = false;
            }
            
            // Closes any screens that the user may have had open except the help screen
            closeAllScreens();
            
        // Otherwise print a message
        } else {
            
            // Prints a message that lets them know that they are not logged in
            javax.swing.JOptionPane.showMessageDialog(null, "You are not logged in!", "Logout", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        }
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void manageAccountsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountsMenuItemActionPerformed
        
        // This method is triggered when the Manage Accounts menu item is clicked under File
        
        // If the person is logged in as an administrator
        if (isLoggedIn && isLoggedInAsAdmin) {
            
            // Creates a new instance of the manage accounts screen
            manageAccounts = new ManageAccounts();
            
            // Adds the screen to the desktop pane
            desktopPane.add(manageAccounts);
            
            // Brings the screen to the front
            manageAccounts.toFront();
            
            // Sets the variable isManageScreenOpen to true
            isManageScreenOpen = true;
            
        // If the person is not logged in as an administrator            
        } else {
            
            // A message pops up
            javax.swing.JOptionPane.showMessageDialog(null, "You must be logged in as an administrator!", "Manage Accounts", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_manageAccountsMenuItemActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        if (isLoggedIn) {
            // Code to open main menu
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "You are not logged in!", "Home", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_homeButtonActionPerformed

    private void printerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printerButtonActionPerformed
        // TODO add your handling code here:
        if (isLoggedIn) {
            // Code to open the print report screen
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "You are not logged in!", "Print Reports", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_printerButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        if (!isHelpScreenOpen) {
            HelpScreen help = new HelpScreen();
            desktopPane.add(help);
            help.toFront();
            isHelpScreenOpen = true;
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Help is already open", "Help", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem manageAccountsMenuItem;
    private javax.swing.JButton printerButton;
    private javax.swing.JLabel starsLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
